osc=no # デフォルトのUIを無効化します。
#border = no # ModernXではボーダーを無効化するのが推奨されている

vo=gpu-next
dither-depth=8
deband=yes
gpu-api=d3d11
gpu-context=d3d11
correct-downscaling=yes
sigmoid-upscaling=yes

hwdec=nvdec-copy
hwdec-codecs=av1

# ============================
#  画面サイズ＆音量
# ============================
# [window-size]
autofit-larger=50%
keep-open=yes
idle=yes
# volume-save=yes

# ============================
#  Scaling (VTuber / アニメ向け)
# ============================
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
tscale=oversample


# ============================
#  Motion / Sync (180Hz最適化)
# ============================
# [interp-180hz]
# video-sync=display-resample
# interpolation=yes
# tscale=oversample
# tscale-window=sphinx
# tscale-radius=1.5
# interpolation-threshold=0.01   # 180Hz向けに補間の遅延を最小化

# # 補間弱め（自然）
[interp-60]
profile-cond=container-fps >= 50
interpolation=yes
tscale=oversample
tscale-radius=1.2
interpolation-threshold=0.015

# # 補間強め（ヌルヌル）
# [interp-30]
# profile-cond=container-fps >= 25 and container-fps < 50
# interpolation=yes
# tscale=oversample
# tscale-radius=2.0
# interpolation-threshold=0.008

# # ジャダー消し特化
# [interp-24]
# profile-cond=container-fps < 25
# interpolation=yes
# tscale=oversample
# tscale-radius=1.8
# interpolation-threshold=0.01

# [interp-auto-24]
# profile-cond=estimated-vf-fps < 25
# interpolation=yes
# video-sync=display-resample
# tscale=oversample
# tscale-window=sphinx
# tscale-radius=1.8
# interpolation-threshold=0.01
# profile=window-size

# [interp-auto-30]
# profile-cond=estimated-vf-fps >= 25 and estimated-vf-fps < 50
# interpolation=yes
# video-sync=display-resample
# tscale=oversample
# tscale-window=sphinx
# tscale-radius=2.0
# interpolation-threshold=0.008
# profile=window-size

# [interp-auto-60]
# profile-cond=estimated-vf-fps >= 50
# interpolation=yes
# video-sync=display-resample
# tscale=oversample
# tscale-window=sphinx
# tscale-radius=1.2
# interpolation-threshold=0.015
# profile=window-size

# [interp-auto-120]
# profile-cond=display-fps >= 110 and display-fps < 170 and estimated-vf-fps >= 50
# interpolation=yes
# video-sync=display-resample
# tscale=oversample
# tscale-window=sphinx
# tscale-radius=1.1
# interpolation-threshold=0.012
# profile=window-size

# [interp-auto-180]
# profile-cond=display-fps >= 170 and estimated-vf-fps >= 50
# interpolation=yes
# video-sync=display-resample
# tscale=oversample
# tscale-window=sphinx
# tscale-radius=1.0
# interpolation-threshold=0.010
# profile=window-size


[thumbfast]
profile-cond='eq(get("script-name"), "thumbfast")'
scale=bilinear
dscale=bilinear
cscale=bilinear
sigmoid-upscaling=no
correct-downscaling=no
deband=no
hwdec=no
interpolation=no
video-sync=audio
